#include "PythonGenerator.hpp"

#include <iomanip>
#include <ostream>
#include <sstream>
#include <stdexcept>

void PythonGenerator::generate(const Program& program, std::ostream& out) const {
    out << "# Generated by the Bangla compiler\n\n";
    if (program.statements.empty()) {
        out << "pass\n";
        return;
    }
    for (const auto& statement : program.statements) {
        generateStmt(*statement, out, 0);
    }
}

void PythonGenerator::generateStmt(const Stmt& stmt, std::ostream& out, int indent) {
    writeIndent(out, indent);

    if (const auto* declaration = dynamic_cast<const VarDeclStmt*>(&stmt)) {
        out << declaration->name << " = ";
        if (declaration->initializer) {
            out << generateExpr(*declaration->initializer);
        } else if (declaration->declaredType == ValueType::Int) {
            out << "0";
        } else {
            out << "\"\"";
        }
        out << '\n';
        return;
    }
    if (const auto* assignment = dynamic_cast<const AssignStmt*>(&stmt)) {
        out << assignment->name << " = " << generateExpr(*assignment->value) << '\n';
        return;
    }
    if (const auto* print = dynamic_cast<const PrintStmt*>(&stmt)) {
        out << "print(" << generateExpr(*print->value) << ")\n";
        return;
    }
    if (const auto* block = dynamic_cast<const BlockStmt*>(&stmt)) {
        if (block->statements.empty()) out << "pass\n";
        else { out << '\n'; generateBlock(*block, out, indent); }
        return;
    }
    if (const auto* ifStmt = dynamic_cast<const IfStmt*>(&stmt)) {
        out << "if " << generateExpr(*ifStmt->condition) << ":\n";
        if (ifStmt->thenBranch->statements.empty()) {
            writeIndent(out, indent + 1); out << "pass\n";
        } else generateBlock(*ifStmt->thenBranch, out, indent + 1);
        if (ifStmt->elseBranch) {
            writeIndent(out, indent); out << "else:\n";
            if (ifStmt->elseBranch->statements.empty()) {
                writeIndent(out, indent + 1); out << "pass\n";
            } else generateBlock(*ifStmt->elseBranch, out, indent + 1);
        }
        return;
    }
    if (const auto* whileStmt = dynamic_cast<const WhileStmt*>(&stmt)) {
        out << "while " << generateExpr(*whileStmt->condition) << ":\n";
        if (whileStmt->body->statements.empty()) {
            writeIndent(out, indent + 1); out << "pass\n";
        } else generateBlock(*whileStmt->body, out, indent + 1);
        return;
    }
    throw std::runtime_error("Python generator encountered an unknown statement");
}

void PythonGenerator::generateBlock(const BlockStmt& block, std::ostream& out, int indent) {
    for (const auto& statement : block.statements) generateStmt(*statement, out, indent);
}

std::string PythonGenerator::generateExpr(const Expr& expr) {
    if (const auto* number = dynamic_cast<const NumberExpr*>(&expr)) return std::to_string(number->value);
    if (const auto* string = dynamic_cast<const StringExpr*>(&expr)) return quoteString(string->value);
    if (const auto* variable = dynamic_cast<const VariableExpr*>(&expr)) return variable->name;
    if (const auto* unary = dynamic_cast<const UnaryExpr*>(&expr)) {
        return "(" + unary->op + generateExpr(*unary->expr) + ")";
    }
    if (const auto* binary = dynamic_cast<const BinaryExpr*>(&expr)) {
        return "(" + generateExpr(*binary->left) + " " + binaryOpName(binary->op) + " " +
               generateExpr(*binary->right) + ")";
    }
    throw std::runtime_error("Python generator encountered an unknown expression");
}

std::string PythonGenerator::quoteString(const std::string& value) {
    std::ostringstream out;
    out << std::quoted(value);
    return out.str();
}

void PythonGenerator::writeIndent(std::ostream& out, int indent) {
    for (int i = 0; i < indent; ++i) out << "    ";
}
